export const SET_SIMPLE_REPAIR = 'APP/SET_SIMPLE_REPAIR'
export const SET_COMPLEX_REPAIR = 'APP/SET_COMPLEX_REPAIR'
export const SET_LOADING = 'APP/SET_LOADING'
export const SET_ERROR = 'APP/SET_ERROR'